FUNC LABEL 0
    MOV REG 0 VAL 10
    MOV STK A VAL 1
    MOV STK B VAL 1
    MOV STK C VAL 0
    PRINT VAL 1
    PRINT VAL 1
    MOV REG 1 VAL 254
    MOV REG 3 VAL 255
    ADD REG 0 REG 1
    MOV REG 1 REG 0
    EQU REG 1
    ADD REG 7 REG 1
    MOV REG 7 VAL 14
    MOV REG 7 VAL 25
    MOV REG 1 STK A
    MOV REG 2 STK B
    ADD REG 1 REG 2
    MOV STK C REG 1
    MOV REG 1 STK B
    MOV STK A REG 1
    MOV REG 1 STK C
    MOV STK B REG 1
    ADD REG 0 REG 3
    PRINT STK C
    MOV REG 7 VAL 9
    RET
