FUNC LABEL 0
    MOV STK A VAL 3
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    PRINT STK b
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV STK A VAL 1
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    PRINT STK b
    CAL VAL 2
    RET
FUNC LABEL 2
    MOV STK A VAL 4
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    PRINT STK b
    CAL VAL 3
    RET
FUNC LABEL 3
    MOV STK A VAL 1
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    PRINT STK b
    CAL VAL 4
    RET
FUNC LABEL 4
    MOV STK A VAL 5
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    PRINT STK b
    CAL VAL 5
    RET
FUNC LABEL 5
    MOV STK A VAL 9
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    PRINT STK b
    CAL VAL 6
    RET
FUNC LABEL 6
    MOV STK A VAL 2
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    PRINT STK b
    CAL VAL 7
    RET
FUNC LABEL 7
    MOV STK A VAL 6
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    MOV STK c STK b
    PRINT STK c
    RET
