FUNC LABEL 0
    MOV STK A VAL 5
    MOV STK B VAL 7
    MOV REG 2 VAL 0
    MOV REG 0 STK A
    MOV REG 1 REG 0
    EQU REG 1
    ADD REG 7 REG 1
    MOV REG 7 VAL 9
    MOV REG 7 VAL 14
    MOV REG 3 STK B
    ADD REG 2 REG 3
    MOV REG 1 VAL 255
    ADD REG 0 REG 1
    MOV REG 7 VAL 4
    PRINT REG 2
    RET
