FUNC LABEL 0
    MOV REG 0 VAL 10
    MOV REG 2 VAL 0
    CAL VAL 1
    PRINT REG 2
    RET
FUNC LABEL 1
    MOV REG 1 REG 0
    ADD REG 2 REG 0
    MOV REG 3 VAL 255
    ADD REG 0 REG 3
    EQU REG 1
    ADD REG 7 REG 1
    CAL VAL 1
    RET
