FUNC LABEL 0
    MOV STK A VAL 69
    MOV STK B STK A
    MOV STK C STK B
    MOV STK D STK C
    MOV STK E STK D
    MOV STK F STK E
    MOV STK G STK F
    MOV STK H STK G
    MOV STK I STK H
    MOV STK J STK I
    MOV STK K STK J
    MOV STK L STK K
    MOV STK M STK L
    MOV STK N STK M
    MOV STK O STK N
    MOV STK P STK O
    MOV STK Q STK P
    MOV STK R STK Q
    MOV STK S STK R
    MOV STK T STK S
    MOV STK U STK T
    MOV STK V STK U
    MOV STK W STK V
    MOV STK X STK W
    MOV STK Y STK X
    MOV STK Z STK Y
    MOV STK a STK Z
    MOV STK b STK a
    MOV STK c STK b
    PRINT STK c
    RET
